### ISSUE TITLE
[Feature Request] Full screen applications support on Linux

### ISSUE THREAD

**Issue by dev-rfc** [Hacksore/overlayed#33]
Hey there!

First I want to thank you for making this project, it's a great tool and works really well!

I want to ask you if there is any way of making it over a full screen application, like a game window, or simply a full screen application.

Using Plasma on Wayland, the application is decorated by the Kwin Window System

![image](https://github.com/Hacksore/overlayed/assets/16182725/d8002c9d-4878-4896-a039-20cef256b3e0)

That one is easy to fix in KDE, the user just need to make a rule to remove the title bar. However, the full screen issue is not that simple.

Since it's a "window", even if you force it to appear above the others, a full screen application will always take precedence and appear over the application. 

This is due the FreeDesktop Window Manager specification, so it's very unlikely it can be circumvented with the tools provided by the desktop environment.

It would be very useful if we could have this feature built in the application.

Again, thank you for the project!

**Comment by Hacksore** [comment]
I'm assume it's the same issue as windows/macOS with fullscreen games.

When I play on Windows/macOS I use borderless window mode.

AFAIK there is no way for tauri, the desktop app framework, to render over "real" fullscreen things.

**Comment by dev-rfc** [comment]
Actually it happens even with borderless windows (on Plasma). However, this seems to be a Plasma issue, as it works with borderless windows on Gnome.

Searching about, I found this issue:

- https://bugs.kde.org/show_bug.cgi?id=439573

Which is basically the same. They have implemented a workaround, which is OSD type of window that we can use by setting a custom rule,  but...

- https://www.mail-archive.com/kde-bugs-dist@kde.org/msg782593.html

... It doesn't work with Wayland. 😅

So I'm closing the issue, it's probably something that needs to be addressed on KDE's side.

Thank you for your attention and sorry to bother!

**Comment by Hacksore** [comment]
we can blame everything on Wayland 😂
